import React, { useEffect } from "react";
import { Download } from "lucide-react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { python } from "@codemirror/lang-python";
import { cpp } from "@codemirror/lang-cpp";
import { html } from "@codemirror/lang-html";
import { dracula } from "@uiw/codemirror-theme-dracula";
import ACTIONS from "../Action";
import { LANGUAGES } from "../config";

function EditorComp({
  socketRef,
  roomId,
  onCodeChange,
  language,
  onLanguageChange,
  theme,
  code,
  onRunCode,
  isExecuting,
  onLanguageSelect,
  onThemeSelect,
  isLightMode,
  isMobile,
  onDownload,
}) {
  const [editorCode, setEditorCode] = React.useState(code || "");

  useEffect(() => {
    const socket = socketRef.current;
    if (socket) {
      socket.on(ACTIONS.CODE_CHANGE, ({ code: incomingCode }) => {
        if (incomingCode !== null) {
          setEditorCode(incomingCode);
          onCodeChange(incomingCode);
        }
      });
    }
    return () => {
      socket?.off(ACTIONS.CODE_CHANGE);
    };
  }, [socketRef, onCodeChange]);

  useEffect(() => {
    if (code !== undefined && code !== editorCode) {
      setEditorCode(code);
    }
  }, [code, editorCode]);

  const handleEditorChange = (value, viewUpdate) => {
    setEditorCode(value);
    onCodeChange(value);
    localStorage.setItem(`code-${roomId}`, value);

    // Check if change generated by human input
    if (viewUpdate.transactions[0]?.isUserEvent("input") || viewUpdate.transactions[0]?.isUserEvent("delete")) {
      socketRef.current?.emit(ACTIONS.CODE_CHANGE, {
        roomId,
        code: value,
      });
    }
  };

  const getLanguageExtension = (lang) => {
    switch (lang) {
      case "javascript": return javascript({ jsx: true });
      case "python": return python();
      case "cpp": return cpp();
      case "java": return cpp();
      case "htmlmixed": return html();
      default: return javascript();
    }
  };


  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", backgroundColor: "var(--bg-dark)" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "8px 16px", backgroundColor: "var(--bg-card)", borderBottom: "1px solid var(--border-color)" }}>

        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <div style={{ fontSize: "14px", fontWeight: "600", color: "var(--text-main)", opacity: 0.8 }}>
            main.{language === "javascript" ? "js" : language === "python" ? "py" : language === "cpp" ? "cpp" : "java"}
          </div>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
          {isMobile && (
            <button
              onClick={onDownload}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                width: "32px",
                height: "32px",
                color: "var(--text-muted)",
                backgroundColor: "var(--secondary)",
                borderRadius: "6px",
                border: "1px solid var(--border-color)",
                cursor: "pointer",
                transition: "all 0.2s"
              }}
              onMouseOver={(e) => e.currentTarget.style.borderColor = "var(--primary)"}
              onMouseOut={(e) => e.currentTarget.style.borderColor = "var(--border-color)"}
              title="Download Code"
            >
              <Download size={16} />
            </button>
          )}

          <select
            value={language}
            onChange={(e) => onLanguageChange(e.target.value)}
            style={{
              backgroundColor: "var(--secondary)",
              border: "1px solid var(--border-color)",
              color: "var(--text-muted)",
              fontSize: "12px",
              fontWeight: "500",
              outline: "none",
              cursor: "pointer",
              padding: "4px 10px",
              borderRadius: "6px",
              transition: "all 0.2s"
            }}
            onMouseOver={(e) => e.target.style.borderColor = "var(--primary)"}
            onMouseOut={(e) => e.target.style.borderColor = "var(--border-color)"}
          >
            {LANGUAGES.map(l => (
              <option key={l.value} value={l.value} style={{ backgroundColor: "var(--bg-card)", color: "var(--text-main)" }}>{l.name}</option>
            ))}
          </select>
        </div>

      </div>

      <div style={{ flex: 1, overflow: "auto", fontSize: "16px" }}>
        <CodeMirror
          value={editorCode}
          height="100%"
          theme={isLightMode ? "light" : dracula}
          extensions={[getLanguageExtension(language)]}
          onChange={handleEditorChange}
          basicSetup={{
            lineNumbers: true,
            indentOnInput: true,
            bracketMatching: true,
            closeBrackets: true,
            autocompletion: true,
            rectangularSelection: true,
            crosshairCursor: true,
            highlightActiveLine: true,
            highlightSelectionMatches: true,
          }}
          style={{ height: "100%" }}
        />
      </div>
    </div>
  );
}

export default EditorComp;
