const ACTIONS = {
  JOIN: "join",
  JOINED: "joined",
  DISCONNECTED: "disconnected",
  CODE_CHANGE: "code-change",
  SYNC_CODE: "sync-code",
  LEAVE: "leave",
  SEND_MESSAGE: "send-message",
  RECEIVE_MESSAGE: "receive-message",
  SYNC_EXECUTE: "sync-execute",
  SYNC_OUTPUT: "sync-output",
  SYNC_LANGUAGE: "sync-language",
  EDIT_MESSAGE: "edit-message",
  DELETE_MESSAGE: "delete-message",
  SYNC_CHAT: "sync-chat",
  CURSOR_MOVE: "cursor-move",
  WHITEBOARD_DRAW: "whiteboard-draw",
  WHITEBOARD_CLEAR: "whiteboard-clear",
  PROJECT_JOIN: "project-join",
  FILE_CHANGE: "file-change",
  MOUSE_MOVE: "mouse-move",
  FOLLOW_MODE: "follow-mode",
  WHITEBOARD_CURSOR: "whiteboard-cursor",
  SYNC_SCROLL: "sync-scroll",
  SCREEN_SHARE_START: "screen-share-start",
  SCREEN_SHARE_STOP: "screen-share-stop",
  MEDIA_STATE_CHANGE: "media-state-change",
  WHITEBOARD_SYNC_REQUEST: "whiteboard-sync-request",
  WHITEBOARD_SYNC: "whiteboard-sync",
};

module.exports = ACTIONS;
